# Generated by Django 5.1.6 on 2025-06-05 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='course/image')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseImage', to='course.course')),
            ],
        ),
    ]
