# Generated by Django 5.1.6 on 2025-06-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_courseimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='subject/image')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectImage', to='course.subject')),
            ],
        ),
    ]
