# Generated by Django 5.1.6 on 2025-07-29 08:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_subjectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
