# Generated by Django 5.1.6 on 2025-10-30 19:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_courseimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
